version: "3.7"

services:
  database:
    image: mysql:latest
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=swordfish
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"

  data-ingestion:
    image: data-ingestion
    build: images/data-ingestion
    command: ["./run.py"]
    volumes:
      - ./data:/data

  data-summary:
    image: data-summary
    build: images/data-summary
    command: ["./run.py"]
    volumes:
      - ./apps/data-summary/sql:/sql
      - ./data:/data